name: spatial_args
channels:
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - jupyterlab
  - tskit
  - msprime
  - numpy
  - pandas
  - matplotlib
  - IPython
  - pip:
    - tskit_arg_visualizer
    - geoancestry
    - "git+https://github.com/osmond-lab/sparg.git"