name: spatial_args2
channels:
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - jupyterlab
  - tskit
  - msprime
  - numpy
  - pandas
  - matplotlib
  - IPython
  - pip:
    - tskit_arg_visualizer